[project]
name = "project-oop"
version = "0.1.0"
description = ""
authors = [
    {name = "Slayer",email = "chistyakov.andrey.vladimirovic@gmail.com"}
]
readme = "README.md"
package-mode = false
[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
black = "^23.12.0"
flake8 = "^7.0.0"
mypy = "^1.8.0"
isort = "^5.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
# Максимальная длина строки (119 символов — стандарт для Black)
max-line-length = 119

# Список папок, которые линтер должен игнорировать
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv"
]

# Игнорировать специфичные правила, которые конфликтуют с Black
# E203: пробел перед двоеточием (Black часто его ставит в срезах)
# W503: перенос строки перед бинарным оператором
extend-ignore = ["E203", "W503"]


[tool.black]
line-length = 119
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --cov=src --cov-report term-missing"